### ISSUE TITLE
Logging stopping to work after a while in Meteor projects

### ISSUE THREAD

**Issue by lyykfi** [fluent/fluent-logger-forward-node#24]
Hi!

I just want to ask about any ideas why the package could not work with Meteor(we still have to maintain some legacy) projects. It started logging but stop after a while (but there is still console.log logs in console). No errors, just silently stop to work and restart after redeploy.

Winston papertrail plugin worked fine (also based on tcp request as far as I know).
Do you have any ideas? :-)

Thanks in advice.

Andrei

**Comment by jamiees2** [comment]
Hey, I'm sorry, I'm not sure if I understand right. Was the issue resolved with that, or did you manage to figure out the problem?

**Comment by jamiees2** [comment]
I think this might be fixed, we ran into a similar issue in our production code, which was due to a memory leak. I'm gonna assume this is resolved, but let me know if it's not :)
