### ISSUE TITLE
Question: How do we handle deferred promise rejections due to dropped entries?

### ISSUE THREAD

**Issue by mhassan1** [fluent/fluent-logger-forward-node#28]
Thanks for the awesome library!

I am experimenting with the situation where Fluent becomes unreachable while events are being emitted. I believe `sendQueueMaxLimit` is the right way to prevent backpressure, but I noticed that dropped entries cause an `unhandledPromiseRejection`, and I don't see a way to catch the rejection.

Here is a simple reproduction:
```js
const { FluentClient } = require('@fluent-org/logger')
const logger = new FluentClient('testing', {
  socket: {
    host: 'i-dont-exist.com'
  },
  sendQueueMaxLimit: {
    length: 2,
  },
  ack: {}
})

const run = async () => {
  await Promise.all(Array(3).fill().map(async (_, i) => {
    try {
      await logger.emit('label', {
        hello: i
      })
      console.log('written!', i)
    } catch (err) {
      console.error('uh oh!', err.message)
    }
  }))
}

run()
```

This results in `unhandledPromiseRejection: DroppedError`. It seems the `dropEntry.deferred.reject` [here](https://github.com/fluent/fluent-logger-forward-node/blob/85f5a4f875e2dd1be56e239b593438d87cdb6ae9/src/modes/queue.ts#L86) is not bubbled up to the caller.

The only resolution I've found is to add the following:
```js
process.on('unhandledRejection', (reason, promise) => {
  if (reason instanceof FluentError.DroppedError) return
  throw promise
})
```

Is there a correct way to handle this that I am missing?

**Comment by jamiees2** [comment]
Thanks for the bug report! After scratching my head at this for a bit, I figured out that this was a misunderstanding on my part in how `.finally` works :) It's this line: https://github.com/fluent/fluent-logger-forward-node/blob/85f5a4f875e2dd1be56e239b593438d87cdb6ae9/src/client.ts#L476 that's rethrowing the promise, at least when I tried your reproduction, it printed `uh oh!` 3 times correctly, but still had an uncaught promise :) 

I will fix this bug ASAP and cut a new release, thanks so much for reporting!

**Comment by jamiees2** [comment]
v1.0.6 is out with a fix for this! Thanks again for the bug report :)

**Comment by mhassan1** [comment]
Thanks for the quick turnaround!
