### ISSUE TITLE
TLS/SSL encryption does not work

### ISSUE THREAD

**Issue by yunzhe813** [fluent/fluent-logger-forward-node#39]
I've been trying to make TLS/SSL encryption work locally by following the example in the doc, but I cannot. Here are the configs

Fluentd configuration:
```aconf
<source>
  @type forward
  port 24224
  <transport tls>
    ca_cert_path /path/to/ca_cert.pem
    ca_private_key_path /path/to/ca_key.pem
    ca_private_key_passphrase very_secret_passphrase
  </transport>
</source>

<match **.*>
  @type stdout
</match>
```
Logger configuration:
```js
const logger = new FluentClient("tag", {
  socket: {
    host: "localhost",
    port: 24224,
    timeout: 3000, // 3 seconds
  },
  tls: {
    ca: fs.readFileSync("/path/to/ca_cert.pem")
  }
});
```

I can successfully log a message with `openssl` (command is from the [fluentd docs](https://docs.fluentd.org/input/forward#how-to-enable-tls-encryption)):
```bash
echo -e '\x93\xa9debug.tls\xceZr\xbc1\x81\xa3foo\xa3bar' | \
  openssl s_client -connect localhost:24224
```

When I try with the logger, the `emit` promise is resolved, but I get the following error in the Fluentd server:
```
#0 unexpected error before accepting TLS connection by OpenSSL addr="127.0.0.1" host="127.0.0.1" port=56088 error_class=OpenSSL::SSL::SSLError error="SSL_accept returned=1 errno=0 state=error: wrong version number"
```

I tried messing around with TLS versions, but my current guess is that the `ca` parameter gets completely ignored. I get the same error even if I excude the `ca` parameter.

~In `socket.ts`, there is this line: `tls.connect({...this.tlsOptions, ...this.socketParams});`, but the `tls.connect` function doesn't actually seem to take in a parameter called `ca` (per the [Node.js TLS API docs](https://nodejs.org/api/tls.html)). However, `tls.createSecureContext` does seem to accept `ca` to override trusted certificates.~

I'm not sure if I've missed something in setting this up or if the TLS doesn't work with this client.

### Edit
After doing some more digging into the source code, I figured it out. 
```js
const logger = new FluentClient("tag", {
  socket: {
    host: "localhost",
    port: 24224,
    timeout: 3000, // 3 seconds,
    tls: {
      ca: fs.readFileSync("/path/to/ca_cert.pem")
    }
  }, 
});
```

Please correct your documentation.

**Comment by jamiees2** [comment]
ah I understand, I'll correct this, thank you for the report!
